### ISSUE TITLE
Where can I find the convnext model?

### ISSUE THREAD

**Issue by howardgriffin** [lime-j/RDNet#2]
Hi, I wonder where can I find the [convnext model](https://github.com/lime-j/RDNet/blob/fd4fa48a5ee473fef9b30a2cc32e606a399be2a3/models/cls_model_eval_nocls_reg.py#L209)?

**Comment by lime-j** [comment]
Sorry for the inconvenience. We have put the convnext model into https://checkpoints.mingjia.li/cls_model.pth

**Comment by lime-j** [comment]
Please don't hesitate to ask if you have further question. I will reply once I notice it.

**Comment by howardgriffin** [comment]
Another problem, I can't find the model [here](https://github.com/lime-j/RDNet/blob/ee3ace6ec3bdf1faeba9de8c7eadfd1b63c5d6f3/models/arch/RDnet_.py#L167)

**Comment by lime-j** [comment]
You can found it at https://checkpoints.mingjia.li/focal.pth

**Comment by lime-j** [comment]
In fact, this part of parameters are include in our released model.

**Comment by howardgriffin** [comment]
Thank you for your reply. Waiting for the training code be released.(*￣︶￣)
