### ISSUE TITLE
Python and packages versions

### ISSUE THREAD

**Issue by Liampour** [lime-j/RDNet#3]
Hello, 
congratulations for your works, based on the paper seems very promising.

Can you provide more details about python and required packages versions? 
I encounter errors that are resolved with different versions of the installed packages.

There is also a mix-up with the data import folder, when I run the command  `python3 test_sirs.py --icnn_path <path to the main checkpoint> --resume` I meet errors  like: ` No such file or directory: '/opt/datasets/sirs/test/real20_420/transmission_layer/4.jpg'` or `'/test/SIR2/SolidObjectDataset/blended'` 
Could you provide us a folder structure of the dataset? 
I cant understand where should I locate the inputted image.

Thanks

**Comment by lime-j** [comment]
Really sorry for the inconvenience. You can find the "real20_420" folder at [here](https://github.com/mingcv/YTMT-Strategy/releases/tag/data). Currently, I am working on a commercial version of this work, I don't have enough bandwidth for a re-organization of the code recently.
